name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 6

      - run: npm install
      - run: npm run lint
