name: CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:
  schedule:
    - cron: '0 3 * * *' # daily, at 3am

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run lint

  test:
    name: Test - ${{ matrix.os }}/node@${{ matrix.node-version }}/webpack@${{ matrix.webpack-version }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        node-version: [ 10.x ]
        webpack-version: [ ^1, ^2, ^3, ^4, latest, next ]
        include:
          - {os: windows-latest, node-version: 10.x, webpack-version: latest}
          - {os: macos-latest, node-version: 10.x, webpack-version: latest}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Install webpack ${{ matrix.webpack-version }}
        run: npm i webpack@${{ matrix.webpack-version }}
      - run: npm run test
